### Obtener todos los emprendedores
GET http://localhost:4000/api/entrepreneurs
Content-Type: application/json

### Obtener un emprendedor específico por ID
GET http://localhost:4000/api/entrepreneurs
Content-Type: application/json

### Crear un nuevo emprendedor
POST http://localhost:4000/api/entrepreneurs
Content-Type: application/json

{
    "firstName": "Mauro",
    "lastName": "Mauro",
    "email": "Mauro@example.com",
    "businessName": "John'sk Business",
    "products": [
        {
            "name": "Mauro",
            "description": "Description for producmt 1",
            "price": 100,
            "image": "https://example.com/product1.jpg"
        }
    ]
}

### Actualizar un emprendedor existente
PATCH http://localhost:4000/api/entrepreneurs/4
Content-Type: application/json

{
    "firstName": "Jane",
    "lastName": "Doe",
    "email": "jassssne.doe@example.com",
    "businessName": "Jane's Business",
    "products": [
        {
            "id": 20,
            "name": "Updadsted Product 20",
            "description": "Updated description for product 1",
            "price": 150
        }
    ]
}

### Eliminar un emprendedor
DELETE http://localhost:4000/api/entrepreneurs/1
Content-Type: application/json


