### Obtener todos los emprendedores
GET http://localhost:4000/api/entrepreneurs
Content-Type: application/json

### Obtener un emprendedor específico por ID
GET http://localhost:4000/api/entrepreneurs/1
Content-Type: application/json

### Crear un nuevo emprendedor
POST http://localhost:4000/api/entrepreneurs
Content-Type: application/json

{
  "email": "nn@correo.com",
  "firstName": "Hola",
  "lastName": "Hola",
  "description": "Descripción del emprendedor",
  "businessName": "Nombre del negocio",
  "businessDescription": "Descripción del negocio",
  "products": [
    {
      "name": "Nombrse del Producto",
      "description": "Descripción del producto",
      "price": 99.99
    }
  ]  
}